### ISSUE TITLE
Nuget package is not found, api link is broken

### ISSUE THREAD

**Issue by McHeff** [DevExpress/RazorComponents#1]
So this is amazing, the fact that dev express has controls for Blazor... 

What's not amazing is that the link is broken, and inherently you can't find the nuget package...

**Comment by Mehul** [comment]
Did you add this link to your visual studio Nuget package sources?
https://nuget.devexpress.com/early-access/api

**Comment by SergeySeleznyov** [comment]
I have added the following step to the instruction:

> 3. Install the "DevExpress.RazorComponents" NuGet package.

Also, please check that you have the tag helper and namespaces registered:

> @using DevExpress.RazorComponents
> @addTagHelper *, DevExpress.RazorComponents

 Would you please try it and let us know if it works for you now?

**Comment by McHeff** [comment]
![image](https://user-images.githubusercontent.com/47241975/55466718-07102c80-5600-11e9-81b7-31ba2200d5d0.png)

This is what I get when I click on this link: https://nuget.devexpress.com/early-access/api

**Comment by SergeySeleznyov** [comment]
Please, use it link to add new NuGet source in Visual Studio 2019 "Tools"/"NuGet Package Manager"/"Package Manager Settings". In "Options" dialog open "NuGet Package Manager"/"Package Source". Add new source with Source="https://nuget.devexpress.com/early-access/api".

Does it help?

I will update instruction shortly.

**Comment by SergeySeleznyov** [comment]
I have updated the instruction. Would you please check it whether it is more helpful now?

**Comment by McHeff** [comment]
It looks much better, thank you!

**Comment by SergeySeleznyov** [comment]
Thank you for your feedback we really appreciate it!

**Comment by zac-at-incycle** [comment]
> Please, use this link to add new NuGet source in Visual Studio 2019 "Tools"/"NuGet Package Manager"/"Package Manager Settings". In "Options" dialog open "NuGet Package Manager"/"Package Source". Add new source with Source="https://nuget.devexpress.com/early-access/api".
> 
> Does it help?
> 
> I will update instruction shortly.

This appears to still be an issue.  We cannot access the package because there are no packages currently available at the URL quoted above.  Save result as mentioned by @McHeff previously: empty package feed.

**Comment by CodeKarno** [comment]
@zac-at-incycle 
The [https://nuget.devexpress.com/early-access/api](https://nuget.devexpress.com/early-access/api) feed provides pre-release versions only. It's necessary to enable the "Include prerelease" option in Visual Studio to see the packages: [The "Early Access" NuGet Feed is empty in Visual Studio](https://github.com/DevExpress/RazorComponents#2-the-early-access-nuget-feed-is-empty-in-visual-studio)

**Comment by zac-at-incycle** [comment]
That worked.  Thank you.

**Comment by SergeySeleznyov** [comment]
Hi @McHeff , @zac-at-incycle ,

Our webinar about the Blazor is going to start soon:
https://www.devexpress.com/support/webinars/
Would be great to see you there.
