### ISSUE TITLE
Installation Q

### ISSUE THREAD

**Issue by BenHayat** [DevExpress/RazorComponents#2]
Hi;

I'm trying to follow your installation steps when creating a new project, but the following line is not clear. Can you please clarify where the two client runtime files (dx-razor-components.css  dx-razor-components.js) are supposed to be copied to?

> Obtain the client runtime from this GitHub repository - download all files from the "client-runtime" directory. Include the downloaded files into your start page.

**Comment by BenHayat** [comment]
Figured it out. But the doc needs to be more clear.

**Comment by SergeySeleznyov** [comment]
Hi,
 
Thank you for your suggestion. I've enhanced the instruction. Would you please check it out?

**Comment by BenHayat** [comment]
> Obtain the client runtime directory from the GitHub repository - download all files from this directory. Put the downloaded files in the "wwwroot" directory of your project. Include that files to your start page.

Thank you Sergey for being active and responsive. Just saw the updated instructions.
Thanks!
..Ben

**Comment by SergeySeleznyov** [comment]
Ben,

You are always welcome. I am happy to help.
