### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by BenHayat** [DevExpress/RazorComponents#3]
I have both download and cloned into two directories for testing.

If I go to Components|Pages|Index.razor (or any page) and change anything, save it and run, none of the changes show up. I tried to do Ctrl-Refresh on the browser but does not help.

Is this a bug or the demo is locked?
Thanks!

**Comment by BenHayat** [comment]
As I further investigated, this is an issue with VS2019 and holding on to the cache.

**Comment by SergeySeleznyov** [comment]
I faced the same issue in VS 2019 (bug appears in VS2019 Preview 4, and not fixed in VS2019 Preview 5 and VS2019 Release versions).

I am cleaning the project before every launch.

Hope MS fix it soon.

**Comment by BenHayat** [comment]
Yes "Clear Solution" is the key.
