### ISSUE TITLE
Are docs being prepared for the components?

### ISSUE THREAD

**Issue by BenHayat** [DevExpress/RazorComponents#5]
Hello Team;

As you guy developing these components, are you supplying docs with it, like the API (Properties, methods, events)?
If yes, what's the link?

Thanks!
..Ben

**Comment by SergeySeleznyov** [comment]
Hello @BenHayat ,

In the current early version we have no documentation.
All the features are shown in our demos. 

I mean:
- there is no feature/API if it is not shown in our demos.
- If you find a feature you like, you see the scenario of its use in code.
